version: 0.1.1
env:
  - JENKINS_NODE_WIN: "Dynamo_Win_004"
  - TIMEOUT: 30
  - TEST_REPORT_FORMAT : "nunit"

check_changelog_updated_on_pr: false
pipeline_os: "Windows"

jenkins_creds:
  - 
    type: secretText
    credentialsId: NUGET_API_KEY
    secretText: ENV_NUGET_API_KEY
  - 
    type: usernamePassword
    credentialsId: NUGET_CREDENTIAL
    username: ENV_NUGET_USERNAME 
    password: ENV_NUGET_PASSWORD

job_parameters:
    -
      type: "string"
      name: "ENVIRONMENT_BRANCH"
      defaultValue: ""
      description: ""
    -
      type: "string"
      name: "ENVIRONMENT_REPO"
      defaultValue: ""
      description: ""
    -
      type: "choice"
      name: "ENVIRONMENT_URL_REPO"
      choices: 
        - ""
        - "git.autodesk.com"
        - "github.com"
      description: ""
    -
      type: "choice"
      name: "ENVIRONMENT_LANGUAGE"
      choices: 
        - "en"
        - "de"
        - "ja"
        - "zh-tw"
      description: ""

build:
  -
    before_scripts:
      - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\PreBuild.ps1"
    scripts:
      - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\PreBuild.ps1"

ci_test:
  tests:
    -
      scripts:
        - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\PreBuild.ps1"
  
  test_report_dir: TestResults
  test_report_pattern:
    format: "nunit"
    pattern: "*.xml"
