version: 0.1.1
env:
  - TIMEOUT: 30

check_changelog_updated_on_pr: false
pipeline_os: "Windows"

job_parameters:
    -
      name: "ENVIRONMENT_BRANCH"
      defaultValue: ""
      description: ""
    -
      name: "ENVIRONMENT_REPO"
      defaultValue: ""
      description: ""

build:
  before_scripts:
    - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\PreBuild.ps1"
