version: 0.1.1
env:
  - TIMEOUT: 30

check_changelog_updated_on_pr: false
pipeline_os: "Windows"

build:
  before_scripts:
    - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\SecondPreBuild.ps1"
