version: 0.1.1

check_changelog_updated_on_pr: false
pipeline_os: "Windows"

job_parameters:
    -
      name: "mi primer parametro"
      defaultValue: 1
      description: "Mi primera descripcion"

build:
  before_scripts:
    - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\PreBuild.ps1"
